default['mysql']['server_root_password'] = 'setyourpassword'
default['wordpress']['mysql']['user'] = 'wordpress'
default['wordpress']['mysql']['password'] = 'setyourpassword'
default['wordpress']['mysql']['dbname'] = 'wordpress'
default['wordpress']['parent_dir'] = '/opt/local/www'
default['wordpress']['dir'] = '/opt/local/www/wordpress'
default['wordpress']['url'] = 'http://ja.wordpress.org/wordpress-3.8.1-ja.tar.gz'
default['wordpress']['language'] = 'ja'
default['wordpress']['keys']['auth'] = 'RnnfC%HUPW*dWAim/OmvE3XFCqZc;Ipzv,tdi.#*W?7CR I%|A>hXYWFy1.$YE*-'
default['wordpress']['keys']['secure_auth'] = 'I9%_f+m~D%~mqxW:M|>Dyv+{,,Q2Xm8$B4wq}tQO^r_6k*lEB6%<.X^`wIE[A#d!'
default['wordpress']['keys']['logged_in'] = 'YC<$Kz5 :Gxf|pp+:]=~t}c>Vl1_*XIv24&%57pb.HB-Q|^j }|-Qm{d)U9tG X:'
default['wordpress']['keys']['nonce'] = '^.iYOQpWzC3H*L~P1)V|xa/Gr!Y2_suz`iLFad&!N9}c~0>Ncc3/`H-r+)IVsY!4'
default['wordpress']['salt']['auth'] = 'v#`nOj@I#Rmi>HbcBk-<U5Xq[cK1R6I/e~J`=a)>KOMJ*fNesp%?VL)#&qHPWe@l'
default['wordpress']['salt']['secure_auth'] = 'W[FDSd,JKL#0)zun2S`/zx>cdGx/5{4|TaOnIgO-Yg!o$m}$)Ta}J,7v-i^(+C*i'
default['wordpress']['salt']['logged_in'] = 'RnmR<N^&(3zaVJWLat.zY4.$3VM/e`+!)^C&M}_YsfAYQ|NUU[;Qq}0W~~ey!aS?'
default['wordpress']['salt']['nonce'] = 'X!`}Gz$>FY{.<WtJscPd49}F;<T:dPz}L{-y5?D3+-1RdoJoqg__BPf3<>r#}TVE'